/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Medico____Dot.Bin_Lab;

/**
 *
 * @author USER
 */
public class Hospital_List extends javax.swing.JFrame {

    /**
     * Creates new form Hospital_List
     */
    public Hospital_List() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Goverment_Hospital_List = new javax.swing.JButton();
        Back_Button5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Private_List = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Goverment_Hospital_List.setBackground(new java.awt.Color(102, 255, 102));
        Goverment_Hospital_List.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Goverment_Hospital_List.setForeground(new java.awt.Color(0, 0, 0));
        Goverment_Hospital_List.setText("Goverment Hospital List");
        Goverment_Hospital_List.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 4, true));
        Goverment_Hospital_List.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Goverment_Hospital_List.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        Goverment_Hospital_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Goverment_Hospital_ListActionPerformed(evt);
            }
        });
        getContentPane().add(Goverment_Hospital_List, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 300, 50));

        Back_Button5.setBackground(new java.awt.Color(204, 204, 255));
        Back_Button5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Back_Button5.setForeground(new java.awt.Color(0, 0, 0));
        Back_Button5.setText("Back");
        Back_Button5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back_Button5.setPreferredSize(new java.awt.Dimension(90, 30));
        Back_Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_Button5ActionPerformed(evt);
            }
        });
        getContentPane().add(Back_Button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 100, 50));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Hospital List");
        jButton1.setToolTipText("");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 200, 50));

        Private_List.setBackground(new java.awt.Color(102, 255, 102));
        Private_List.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Private_List.setForeground(new java.awt.Color(0, 0, 0));
        Private_List.setText("Private Hospital List");
        Private_List.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 4, true));
        Private_List.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Private_List.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Private_ListActionPerformed(evt);
            }
        });
        getContentPane().add(Private_List, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 300, 50));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Footlight MT Light", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Project Medico");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, -1, -1));

        jButton5.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 153, 255));
        jButton5.setText("Dot.Bin Lab");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 760, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Medico____Dot/Bin_Lab/Hospital List.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Back_Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_Button5ActionPerformed
        new A_Front_Home_Page().setVisible(true);
    }//GEN-LAST:event_Back_Button5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Goverment_Hospital_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Goverment_Hospital_ListActionPerformed
        new Gov_Hospital_List().setVisible(true);
    }//GEN-LAST:event_Goverment_Hospital_ListActionPerformed

    private void Private_ListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Private_ListActionPerformed
        new Private_Hospital_List().setVisible(true);
    }//GEN-LAST:event_Private_ListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital_List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Hospital_List().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button5;
    private javax.swing.JButton Goverment_Hospital_List;
    private javax.swing.JButton Private_List;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
