/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Medico____Dot.Bin_Lab;

/**
 *
 * @author USER
 */
public class Your_Profile extends javax.swing.JFrame {

    /**
     * Creates new form Your_Profile
     */
    public Your_Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit_From_Program = new javax.swing.JButton();
        Text_Panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Background_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit_From_Program.setBackground(new java.awt.Color(255, 102, 102));
        Exit_From_Program.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Exit_From_Program.setForeground(new java.awt.Color(0, 0, 0));
        Exit_From_Program.setText("Back To Main Programm");
        Exit_From_Program.setToolTipText("");
        Exit_From_Program.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 2, true));
        Exit_From_Program.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        Exit_From_Program.setMaximumSize(new java.awt.Dimension(200, 30));
        Exit_From_Program.setMinimumSize(new java.awt.Dimension(200, 30));
        Exit_From_Program.setPreferredSize(new java.awt.Dimension(200, 35));
        Exit_From_Program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_From_ProgramActionPerformed(evt);
            }
        });
        getContentPane().add(Exit_From_Program, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, -1, -1));

        Text_Panel.setBackground(new java.awt.Color(0, 102, 102));
        Text_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 255));
        jButton1.setText("Loading Your Profile...\n");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Text_Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 370, 100));

        getContentPane().add(Text_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 209, 550, 290));

        Background_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Medico____Dot/Bin_Lab/xd.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        Background_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        getContentPane().add(Background_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_From_ProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_From_ProgramActionPerformed
        new A_Front_Home_Page().setVisible(true);
    }//GEN-LAST:event_Exit_From_ProgramActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Your_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Your_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Your_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Your_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Your_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background_Panel;
    private javax.swing.JButton Exit_From_Program;
    private javax.swing.JPanel Text_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
